### ISSUE TITLE
Can't use `dotnet` without root

### ISSUE THREAD

**Issue by danyhoron** [ptr727/VSCode-Server-DotNetCore#14]
Unable to run: `dotnet build` without root permissions.

I'm getting the following exception on: `dotnet build`

```
abc@ptr727-vscode-server-dotnetcore-1:~/workspace/test-proj-01$ dotnet build
System.UnauthorizedAccessException: Access to the path '/usr/share/dotnet/.dotnet' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by ptr727** [comment]
Need more info if you would like help, e.g. how did you create the container, what are you running on, steps, etc.

**Comment by danyhoron** [comment]
Code-server has rights to edit mounted files. It has issues accessing the dotnet binary inside the container.
If you give me an email address, I can send you credentials to connect to it.

**Comment by danyhoron** [comment]
Here's another interesting thing:

This works:
```
abc@ptr727-vscode-server-dotnetcore-1:~/workspace$ dotnet --version
7.0.400
```
This does not:

```
abc@ptr727-vscode-server-dotnetcore-1:~/workspace$ dotnet new 
System.UnauthorizedAccessException: Access to the path '/usr/share/dotnet/.dotnet' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by danyhoron** [comment]
I found the issue.
Removing: `DOTNET_CLI_HOME` and `DOTNET_ROOT` env vars fixed it.

**Comment by ptr727** [comment]
I remove `DOTNET_CLI_HOME` from the build, it "should" use the default `HOME` directory, that will default to `/config`, or the `user`.
